/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#55006c',
        'on-tertiary-fixed-variant': '#004f56',
        'on-secondary-container': '#fff0fc',
        'inverse-on-surface': '#3c2849',
        'primary-fixed-dim': '#e7b4ff',
        'surface-container-lowest': '#180624',
        'on-primary': '#500075',
        'on-primary-fixed-variant': '#7100a4',
        'surface-container-highest': '#412d4e',
        'error-container': '#93000a',
        'primary-fixed': '#f6d9ff',
        'secondary-fixed-dim': '#f2afff',
        'secondary-fixed': '#fcd7ff',
        'tertiary-fixed-dim': '#89d2dc',
        'on-secondary-fixed': '#340043',
        'surface-container': '#2a1837',
        'inverse-primary': '#8d2cc0',
        'inverse-surface': '#f3daff',
        'background': '#1d0b2a',
        'on-secondary-fixed-variant': '#780097',
        'outline': '#9a8c9e',
        'surface-container-high': '#352242',
        'surface-tint': '#e7b4ff',
        'on-tertiary': '#00363c',
        'on-error-container': '#ffdad6',
        'primary-container': '#7605aa',
        'surface-dim': '#1d0b2a',
        'on-tertiary-container': '#7dc6d0',
        'surface-bright': '#453152',
        'error': '#ffb4ab',
        'on-tertiary-fixed': '#001f23',
        'secondary': '#f2afff',
        'on-primary-container': '#e0a2ff',
        'surface-container-low': '#261333',
        'surface': '#1d0b2a',
        'tertiary': '#89d2dc',
        'tertiary-container': '#00535b',
        'outline-variant': '#4e4352',
        'on-primary-fixed': '#300049',
        'on-surface-variant': '#d1c1d4',
        'tertiary-fixed': '#a5eff9',
        'surface-variant': '#412d4e',
        'on-background': '#f3daff',
        'secondary-container': '#b807e6',
        'on-error': '#690005',
        'on-surface': '#f3daff',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-mobile': '0.75rem',
        'margin': '3rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        'display-hero': ['"Space Grotesk"', 'sans-serif'],
        'display-hero-mobile': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-sm': ['"Space Grotesk"', 'sans-serif'],
        'subheading-accent': ['"Syne"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'subheading-accent': ['22px', { lineHeight: '30px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      maxWidth: {
        'container': '1360px',
      },
    },
  },
  plugins: [],
}
